# RT-Cache Action Pattern Configuration
# This file defines custom action sequences for robot data collection
# Users can modify these patterns to match their specific robot tasks

action_patterns:
  # Simple pick and place pattern
  simple_pick:
    description: "Basic pick and place with 5 phases"
    phases:
      approach:
        steps: [1, 5]
        action: [0.02, 0, 0]  # Move forward towards object
        description: "Approach object"
      
      descend:
        steps: [6, 8]
        action: [0, 0, -0.05]  # Lower gripper
        description: "Descend to grasp height"
      
      grasp:
        steps: [9, 12]
        action: [0, 0, 0]  # Close gripper (handled separately)
        description: "Grasp object"
      
      lift:
        steps: [13, 15]
        action: [0, 0, 0.05]  # Lift object
        description: "Lift object"
      
      release:
        steps: [16, 20]
        action: [0, 0, 0]  # Open gripper and retreat
        description: "Release object"

  # More complex manipulation pattern
  complex_manipulation:
    description: "Multi-step manipulation with precise movements"
    phases:
      initial_approach:
        steps: [1, 3]
        action: [0.03, 0.01, 0]
      
      fine_approach:
        steps: [4, 6]
        action: [0.01, 0, -0.02]
      
      grasp_preparation:
        steps: [7, 9]
        action: [0, 0, -0.03]
      
      execute_grasp:
        steps: [10, 12]
        action: [0, 0, 0]
      
      lift_and_rotate:
        steps: [13, 16]
        action: [0, 0, 0.04]
      
      transport:
        steps: [17, 20]
        action: [-0.02, 0.03, 0]
      
      place:
        steps: [21, 25]
        action: [0, 0, -0.04]
      
      retreat:
        steps: [26, 30]
        action: [-0.01, 0, 0.02]

# Episode groupings for different experimental setups
episode_map:
  # Standard viewpoint-based groupings
  wrist: [1, 2, 3, 4, 5, 6, 7, 8, 9]
  side: [10, 11, 12, 13, 14, 15, 16, 17, 18]
  front: [19, 20, 21, 22, 23, 24, 25, 26, 27]
  
  # Object-based groupings
  all_object_1sample_allview: [1, 4, 7, 10, 13, 16, 19, 22, 25]
  all_object_2sample_allview: [1, 2, 4, 5, 7, 8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25, 26]
  one_object_allview: [1, 2, 3, 10, 11, 12, 19, 20, 21]
  two_object_allview: [1, 2, 3, 4, 5, 6, 10, 11, 12, 13, 14, 15, 19, 20, 21, 22, 23, 24]
  
  # Complete sets
  all: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
  
  # Testing subsets
  test_small: [1, 2, 3]
  test_medium: [1, 5, 10, 15, 20, 25]
  
  # Custom experimental conditions
  baseline_episodes: [1, 10, 19]  # One episode per viewpoint
  validation_episodes: [3, 12, 21]  # Validation set
  challenging_episodes: [6, 15, 24]  # Difficult manipulation cases

# Generator-specific settings
generator_settings:
  default:
    # The default generator uses hardcoded patterns (original RT-Cache behavior)
    max_episodes: 27
    
  configurable:
    # The configurable generator uses this YAML file
    default_pattern: "simple_pick"
    
  random:
    # The random generator creates random actions within bounds
    action_bounds:
      - [-0.05, 0.05]  # x position
      - [-0.05, 0.05]  # y position  
      - [-0.05, 0.05]  # z position
    seed: 42  # For reproducible random sequences